spring:
  application:
    name: KafkaSimple
  kafka:
    consumer:
      auto-offset-reset: earliest
      properties:
        assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
    bootstrap-servers: localhost:9092